# Generated by Django 5.0 on 2024-01-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='meet_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
